# Generated by Django 5.0.4 on 2024-04-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_image_created_at_image_updated_at_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='categories/%Y/%m'),
        ),
    ]
